### ISSUE TITLE
Version 2.11.3: Receiving "Notice: Array to string conversion" on /feed/

### ISSUE THREAD

**Issue by korridor** [siteorigin/siteorigin-panels#818]
The notice occurs at:

`/wp-content/plugins/siteorigin-panels/inc/renderer.php` in `SiteOrigin_Panels_Renderer::the_widget` at line `550`
only on `https://someurl.test/feed/`

Wordpress version: 5.5.1

If you need more information like the stack trace I am happy to provide that for you.

**Comment by AlexGStapleton** [comment]
Hi @korridor,

Thank you for your report. I'm having trouble replicating this error. I've inspected [the line](https://github.com/siteorigin/siteorigin-panels/blame/2.11.3/inc/renderer.php#L550) and it hasn't been adjusted it in a long line so this error must be related to a different line.

Can you please provide a Stack Trace?

Kind regards,
Alex

**Comment by korridor** [comment]
The full stack trace:

```
ErrorException: Notice: Array to string conversion
#32 /wp-includes/formatting.php(1098): wp_check_invalid_utf8
#31 /wp-includes/formatting.php(4496): esc_attr
#30 [internal](0): array_map
#29 /wp-includes/media.php(1094): wp_get_attachment_image
#28 /wp-includes/media.php(2266): gallery_shortcode
#27 /wp-includes/widgets/class-wp-widget-media-gallery.php(129): WP_Widget_Media_Gallery::render_media
#26 /wp-includes/widgets/class-wp-widget-media.php(252): WP_Widget_Media::widget
#25 /wp-content/plugins/siteorigin-panels/inc/renderer.php(550): SiteOrigin_Panels_Renderer::the_widget
#24 /wp-content/plugins/siteorigin-panels/inc/renderer.php(862): SiteOrigin_Panels_Renderer::render_widget
#23 /wp-content/plugins/siteorigin-panels/inc/renderer.php(830): SiteOrigin_Panels_Renderer::render_cell
#22 /wp-content/plugins/siteorigin-panels/inc/renderer.php(756): SiteOrigin_Panels_Renderer::render_row
#21 /wp-content/plugins/siteorigin-panels/inc/renderer.php(336): SiteOrigin_Panels_Renderer::render
#20 /wp-content/plugins/siteorigin-panels/siteorigin-panels.php(337): SiteOrigin_Panels::generate_post_content
#19 /wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#18 /wp-includes/plugin.php(206): apply_filters
#17 /wp-content/plugins/conda-widgets-bundle/includes/conda-widgets-bundle-utilities.php(56): conda_trim_excerpt
#16 /wp-includes/class-wp-hook.php(289): WP_Hook::apply_filters
#15 /wp-includes/plugin.php(206): apply_filters
#14 /wp-includes/formatting.php(3853): wp_trim_excerpt
#13 /wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#12 /wp-includes/plugin.php(206): apply_filters
#11 /wp-includes/post-template.php(429): get_the_excerpt
#10 /wp-includes/feed.php(226): the_excerpt_rss
#9 /wp-includes/feed-rss2.php(103): require_once
#8 /wp-includes/template.php(730): load_template
#7 /wp-includes/functions.php(1611): do_feed_rss2
#6 /wp-includes/class-wp-hook.php(289): WP_Hook::apply_filters
#5 /wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#4 /wp-includes/plugin.php(478): do_action
#3 /wp-includes/functions.php(1573): do_feed
#2 /wp-includes/template-loader.php(48): require_once
#1 /wp-blog-header.php(19): require
#0 /index.php(17): null
``

**Comment by korridor** [comment]
The full stack trace:

```
ErrorException: Notice: Array to string conversion
#32 /wp-includes/formatting.php(1098): wp_check_invalid_utf8
#31 /wp-includes/formatting.php(4496): esc_attr
#30 [internal](0): array_map
#29 /wp-includes/media.php(1094): wp_get_attachment_image
#28 /wp-includes/media.php(2266): gallery_shortcode
#27 /wp-includes/widgets/class-wp-widget-media-gallery.php(129): WP_Widget_Media_Gallery::render_media
#26 /wp-includes/widgets/class-wp-widget-media.php(252): WP_Widget_Media::widget
#25 /wp-content/plugins/siteorigin-panels/inc/renderer.php(550): SiteOrigin_Panels_Renderer::the_widget
#24 /wp-content/plugins/siteorigin-panels/inc/renderer.php(862): SiteOrigin_Panels_Renderer::render_widget
#23 /wp-content/plugins/siteorigin-panels/inc/renderer.php(830): SiteOrigin_Panels_Renderer::render_cell
#22 /wp-content/plugins/siteorigin-panels/inc/renderer.php(756): SiteOrigin_Panels_Renderer::render_row
#21 /wp-content/plugins/siteorigin-panels/inc/renderer.php(336): SiteOrigin_Panels_Renderer::render
#20 /wp-content/plugins/siteorigin-panels/siteorigin-panels.php(337): SiteOrigin_Panels::generate_post_content
#19 /wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#18 /wp-includes/plugin.php(206): apply_filters
#17 [REDACTED]
#16 /wp-includes/class-wp-hook.php(289): WP_Hook::apply_filters
#15 /wp-includes/plugin.php(206): apply_filters
#14 /wp-includes/formatting.php(3853): wp_trim_excerpt
#13 /wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#12 /wp-includes/plugin.php(206): apply_filters
#11 /wp-includes/post-template.php(429): get_the_excerpt
#10 /wp-includes/feed.php(226): the_excerpt_rss
#9 /wp-includes/feed-rss2.php(103): require_once
#8 /wp-includes/template.php(730): load_template
#7 /wp-includes/functions.php(1611): do_feed_rss2
#6 /wp-includes/class-wp-hook.php(289): WP_Hook::apply_filters
#5 /wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#4 /wp-includes/plugin.php(478): do_action
#3 /wp-includes/functions.php(1573): do_feed
#2 /wp-includes/template-loader.php(48): require_once
#1 /wp-blog-header.php(19): require
#0 /index.php(17): null
```

I just realized that custom code of us is part of the stach trace, so I had to redact that line.
I hope it still helps.
I will investigate if this problem has something to do with our custom code from line 17 in the following days.
If this is the case than I am sorry for the inconvenience.

**Comment by AlexGStapleton** [comment]
Thanks. There are references to the gallery widget in your stack trace. I just ran a few tests using that widget and wasn't able to trigger this error. Let me know how you go with your investigation.

**Comment by AlexGStapleton** [comment]
Hi korridor,

Just reaching out to check if you still need help with this.

Kind regards,
Alex

**Comment by Misplon** [comment]
Hi korridor

I'm going to close this issue for the moment. If you still need a hand, please,  let us know.

Cheers

Andrew
